# Generated by Django 4.1.3 on 2023-01-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_image_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
