# Generated by Django 4.1.3 on 2023-01-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_article_views_viewarticle_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='preview',
        ),
    ]
