# Generated by Django 4.1.3 on 2023-01-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ipaddress'),
        ('blog', '0019_articlepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewarticle',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ipaddress'),
        ),
        migrations.DeleteModel(
            name='IpAddress',
        ),
    ]
