# Generated by Django 4.1.3 on 2023-01-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_viewarticle_ip_delete_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepicture',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
    ]
